### ISSUE TITLE
Passing coroutines is forbidden, use tasks explicitly

### ISSUE THREAD

**Issue by pplanteg** [hristo-atanasov/Tasmota-IRHVAC#130] opened 2023-11-25 20:50 UTC
hi,
since last update of home assistant I have this error when I try to set TURBO ON or OFF.

using this yaml code :
          - service: tasmota_irhvac.set_turbo
            data:
              entity_id: climate.clim
              turbo: 'On'
the command work and the state of turbo change but i have the following error message 

home assistant display this error :"Passing coroutines is forbidden, use tasks explicitly"
it's seem related to python 3.11 as i'm reading around 

could you do someting

**Comment by pplanteg** [comment] 2023-11-25 21:08
File "/config/custom_components/tasmota_irhvac/climate.py", line 390, in async_service_handler
    await asyncio.wait(update_tasks)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 425, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.

**Comment by pplanteg** [comment] 2023-11-25 22:15
Hi it look like it's Fixed :)
I have changed in climate.py 
this:
await asyncio.wait(update_tasks)

By: 
await asyncio.gather(*update_tasks)

no more warnnig

**Comment by nao-pon** [comment] 2024-06-28 12:55
Sorry for the late follow-up. I checked with the latest version of this integration (2024.6.2) and was not able to reproduce this issue. Therefore, I will close this, but if you can reproduce it with the latest version, you can reopen this.

**Closed by nao-pon** 2024-06-28 12:55 UTC
