### ISSUE TITLE
The behaviour of hvac item. Missing features.

### ISSUE THREAD

**Issue by ltegzes** [hristo-atanasov/Tasmota-IRHVAC#1] opened 2020-03-01 21:18 UTC
In the middle of the hvac card showing the actual temperature measured by the temperature sensor, it would be nice if it would show the temperature format in xx.x format instead of xx. The hvac item doesn't switch on/off the hvac depending on the difference between the set (requred) and the actual temperature. Is this task left for the hvac to do it? If you want to use automation, than for instance issuing the climate.set_temperature the new value lives only a very-very short  period and it is overwritten  by the graphical setting of the required temperature. The same is valid to the rest of the  result of other climate.setxxx commands. The climate.turn_on, climate.turn_off command doesn't work. Beside these things congratulation to you for your work!

**Comment by hristo-atanasov** [comment] 2020-03-08 21:00
The behavior of Tasmota Irhvac mimics the regular remote. Everything else can be done trough automations. All services works as intended. Graphical glitches are expected as multiple commands are sent almost in a second and the commands are sent in async manner. Closing this issue, as resolved in the HA Community forum.

**Closed by hristo-atanasov** 2020-03-08 21:00 UTC
